# Generated by Django 3.1.3 on 2020-11-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0002_auto_20201119_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='summary',
            field=models.TextField(max_length=100, verbose_name='Professional Summary'),
        ),
    ]
