# Generated by Django 3.1.3 on 2020-11-19 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resumeapp', '0003_auto_20201119_0128'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=20, verbose_name='SkillTest')),
                ('level', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeapp.usersresume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='usersresume',
            name='skilltests',
            field=models.ManyToManyField(blank=True, related_name='user_skill', through='resumeapp.SkillTest', to=settings.AUTH_USER_MODEL, verbose_name='Skill Test'),
        ),
    ]
