# Generated by Django 3.1.3 on 2020-11-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0003_auto_20201119_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='skills', to='resumeapp.Skill', verbose_name='Skill'),
        ),
    ]
